import { z } from 'zod';
import { Core } from './core.ts';
import { assetBody } from './contracts.ts';
import { contextSchema, idSchema, DomainError } from './domain.ts';

export function bootstrap(endpoint = 'http://localhost:4780/mcp') {
  return `# AACL runtime bootstrap v1\n\nAACL is the canonical source for workflows and assets. MCP endpoint: ${endpoint}\n\nStart a session using aacl_session_start. A user-selected /workflow plus additional instructions explicitly starts that workflow. Without a workflow, stay in Advisory / Preparation Mode; do not begin repository modification or PR creation. Discover workflows with aacl_workflow_list; never infer or invent a selection.\n\nBefore execution or delegation, call aacl_context_handoff with the run ID and actual runtime/model. For repository modification request action=development; proceed only when developmentAllowed=true. Apply the returned context and completion criteria. The Core manages state; the external runtime invokes models and tools. Report transitions with aacl_workflow_transition, providing evidence and artifacts. Record observations with aacl_journal_append using the returned snapshot ID.\n\nJournal review is user-triggered in the Core UI. Read an existing review with aacl_review_get and submit proposed changes with aacl_review_submit. Human approval happens in the Core UI. Do not edit generated files as canonical assets.\n`;
}
export function materialize(core: Core, input: unknown) {
  const req = z
    .object({
      runtime: z.enum(['claude', 'codex']),
      context: contextSchema.default({}),
      requested: z.array(idSchema).default([]),
      endpoint: z.string().url().default('http://localhost:4780/mcp'),
    })
    .strict()
    .parse(input);
  const result = core.preview({
    context: { ...req.context, runtime: req.runtime },
    requested: req.requested,
  });
  if (!result.valid) throw new DomainError('CONTEXT_UNRESOLVED', result.errors.join('\n'), 409);
  const skillRoot = req.runtime === 'claude' ? '.claude/skills' : '.agents/skills';
  const files: { path: string; content: string }[] = [
    { path: 'AACL-BOOTSTRAP.md', content: bootstrap(req.endpoint) },
    {
      path: 'AACL-CONTEXT.md',
      content: `<!-- Generated by AACL. Edit canonical assets in the Core. -->\n\n${result.content}\n`,
    },
  ];
  for (const a of result.assets) {
    if (a.type === 'skill')
      files.push({
        path: `${skillRoot}/${a.id}/SKILL.md`,
        content: `---\nname: ${a.id}\ndescription: ${JSON.stringify(a.description || a.name)}\n---\n\n${assetBody(a)}\n`,
      });
    if (a.type === 'workflow')
      files.push({
        path: `${skillRoot}/${a.id}/SKILL.md`,
        content: `---\nname: ${a.id}\ndescription: ${JSON.stringify(a.description || a.name)}\n---\n\nThis is a generated AACL workflow launcher (${a.id}@${a.revision}).\nCall aacl_session_start with workflowId=${a.id} and the user's additional instruction. Then call aacl_context_handoff for the created run. Read AACL-BOOTSTRAP.md for the runtime contract.\n`,
      });
  }
  files.push({
    path: 'aacl-manifest.json',
    content:
      JSON.stringify(
        {
          version: 1,
          generated: true,
          runtime: req.runtime,
          context: result.context,
          assets: result.assets.map((a) => ({ id: a.id, revision: a.revision })),
          files: files.map((f) => f.path),
        },
        null,
        2,
      ) + '\n',
  });
  return { runtime: req.runtime, files, estimatedTokens: result.estimatedTokens };
}
